### ISSUE TITLE
Compatibility issues with pymongo3 & bson3

### ISSUE THREAD

**Issue by boogheta** [twisted/txmongo#80]
Hi, using txmongo for a while I hadn't updated for about a year and am discovering now the new versions.

I tried installing on a blank ubuntu machine both mongo3 (following new method given [here](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/)) then `pip install txmongo==0.6` and resulted in a non-functional install, as shown by the following error when running `python examples/inlinecallbacks/query.py`: 

<pre>
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 424, in errback
    self._startRunCallbacks(fail)
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
    self._runCallbacks()
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1163, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1105, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/tmp/test", line 7, in example
    docs = yield mongo.foo.test.find(limit=10)
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1107, in _inlineCallbacks
    result = g.send(result)
  File "/home/boo/.virtualenvs/hyphe/local/lib/python2.7/site-packages/txmongo/collection.py", line 150, in find
    defer.returnValue([d.decode(as_class=as_class) for d in documents])
exceptions.TypeError: decode() got an unexpected keyword argument 'as_class'
</pre>

For what I understand, it seems txmongo0.6 uses methods from bson2.7 while bson3 (which dropped some kwargs used in txmongo including 'as_class') is shipped with pymongo3 that is coming along naturally with txmongo.

My solution for now for my projects consists in installing first separately pymongo pinned to version 2.7 and then txmongo pinned to 0.6 in my requirements.txt but that can only be temporary.

I tried installing from git sources instead of pip but had the same issue, which makes sense since decode(as_class=as_class) is still being used line 167 of collection.py in the actual repo.

**Comment by psi29a** [comment]
Great find! I've been using txmongo against mongodb 3.0, but not pymongo3.0 so getting this up to date pushes us forward. Cheers!

**Comment by IlyaSkriblovsky** [comment]
I almost have pull request ready that fixes this regression. Will submit in 5 minutes.

**Comment by trenton42** [comment]
@IlyaSkriblovsky Nice! You beat me to it, I was going to put one together after work today.

**Comment by fiorix** [comment]
Great to see some activity here again. :+1:

**Comment by IlyaSkriblovsky** [comment]
Please see #82

**Comment by psi29a** [comment]
So this PR: #81 is no longer necessary with your fix @IlyaSkriblovsky ?

**Comment by IlyaSkriblovsky** [comment]
Yes, now `as_class` works with both pymongo 2.7 and 3.0, no need in pinning pymongo version

**Comment by psi29a** [comment]
Issue closed, thanks @IlyaSkriblovsky !

**Comment by boogheta** [comment]
Wow! That's what I call reactivity! Great job, thanks a lot you guys!
Any chance to get a release 0.7 in pypy soon?

**Comment by psi29a** [comment]
How about 15.0? ;)
